var Woogeen=Woogeen||{};
Woogeen.EventDispatcher=function(d){var c={};d.dispatcher={};d.dispatcher.eventListeners={};c.addEventListener=function(c,e){void 0===d.dispatcher.eventListeners[c]&&(d.dispatcher.eventListeners[c]=[]);d.dispatcher.eventListeners[c].push(e)};c.removeEventListener=function(c,e){var i;i=d.dispatcher.eventListeners[c].indexOf(e);-1!==i&&d.dispatcher.eventListeners[c].splice(i,1)};c.dispatchEvent=function(c){for(var e in d.dispatcher.eventListeners[c.type])if(d.dispatcher.eventListeners[c.type].hasOwnProperty(e))d.dispatcher.eventListeners[c.type][e](c)};return c};
Woogeen.WoogeenEvent=function(d){var c={};c.type=d.type;return c};Woogeen.RoomEvent=function(d){var c=Woogeen.WoogeenEvent(d);c.streams=d.streams;return c};Woogeen.StreamEvent=function(d){var c=Woogeen.WoogeenEvent(d);c.stream=d.stream;c.msg=d.msg;return c};Woogeen.PublisherEvent=function(d){return Woogeen.WoogeenEvent(d)};Woogeen.ServerEvent=function(d){return Woogeen.WoogeenEvent(d)};Woogeen.ChatEvent=function(d){var c=Woogeen.WoogeenEvent(d);c.senderId=d.senderId;c.peerId=d.peerId;return c};
Woogeen.RecorderEvent=function(d){var c=Woogeen.WoogeenEvent(d);c.audio=d.audio;return c};Woogeen=Woogeen||{};
Woogeen.Error={STREAM_LOCAL_ACCESS_DENIED:{code:1101,message:"Cannot access to camera or micphone."},P2P_CONN_SERVER_UNKNOWN:{code:2100,message:"Server unknown error."},P2P_CONN_SERVER_UNAVAILABLE:{code:2101,message:"Server is unavaliable."},P2P_CONN_SERVER_BUSY:{code:2102,message:"Server is too busy."},P2P_CONN_SERVER_NOT_SUPPORTED:{code:2103,message:"Method has not been supported by server"},P2P_CONN_CLIENT_UNKNOWN:{code:2110,message:"Client unknown error."},P2P_CONN_CLIENT_NOT_INITIALIZED:{code:2111,message:"Connection is not initialized."},
P2P_CONN_AUTH_UNKNOWN:{code:2120,message:"Authentication unknown error."},P2P_CONN_AUTH_FAILED:{code:2121,message:"Wrong username or token."},P2P_MESSAGING_TARGET_UNREACHABLE:{code:2201,message:"Remote user cannot be reached."},P2P_CHATROOM_ATTENDEE_EXCEED:{code:2301,message:"Exceed room's limitation"}};Woogeen=Woogeen||{};
Woogeen.Peer=function(d){var c=Woogeen.EventDispatcher({}),f=null,e={},i={},g=[],l=null,t={mandatory:{OfferToReceiveAudio:!0,OfferToReceiveVideo:!0}},n=null;d&&(n={},d.iceServers&&(n.iceServers=function(a){for(var b=[],h=0;h<a.length;h++){var c=a[h];if("[object Array]"==Object.prototype.toString.apply(c.urls))for(var e=0;e<c.urls.length;e++)b.push({url:c.urls[e],username:c.username,credential:c.credential});else b.push({url:c.urls,username:c.username,credential:c.credential})}return b}(d.iceServers)));var u=
function(){c.dispatchEvent(Woogeen.ServerEvent({type:"server-connected"}))},v=function(){for(var a in e){var b=e[a];if(b.state==6||b.state==5){b.connection.close();c.dispatchEvent(Woogeen.ChatEvent({type:"chat-stopped",peerId:b.id,senderId:l}));delete e[a]}}c.dispatchEvent(Woogeen.ServerEvent({type:"server-disconnected"}))},w=function(a){var b=e[a];if(!b){j(a);b=e[a]}if(b.state===1){e[a].state=4;c.dispatchEvent(Woogeen.ChatEvent({type:"chat-invited",senderId:a}))}else b.state===2&&o(b.localStream,
b)},x=function(a){var b=e[a];if(b&&b.connection){b.connection.close();delete e[a]}c.dispatchEvent(Woogeen.ChatEvent({type:"chat-denied",senderId:a}))},y=function(a){var b=e[a];if(b&&b.connection){b.connection.close();c.dispatchEvent(Woogeen.ChatEvent({type:"chat-stopped",peerId:b.id,senderId:a}));delete e[a]}},B=function(a,b){var h=e[a];h&&h.state===5&&(h.connection||m(h));console.log("S->C: "+JSON.stringify(b));if(b.type==="offer")z(h,{message:b});else if(b.type==="answer")A(h,{message:b});else if(b.type===
"candidate"&&(h&&h.state===5||h.state===6)){var c=new RTCIceCandidate({candidate:b.candidate,sdpMid:b.sdpMid,sdpMLineIndex:b.sdpMLineIndex});if(h.connection.localDescription!==null&&h.connection.remoteDescription!==null)if(g.length!==0){g.push(c);for(c=0;c<g.length;c++)h.connection.addIceCandidate(g[c]);g=[]}else h.connection.addIceCandidate(c);else g.push(c)}},C=function(a){e[a]||j(a);if(e[a].state===1&&m(e[a])){e[a].state=2;c.dispatchEvent(Woogeen.ChatEvent({type:"chat-ready",peerId:a}))}},D=function(){c.dispatchEvent(Woogeen.ChatEvent({type:"chat-wait"}))},
E=function(a){l=a},z=function(a,b){if(a&&a.state===3||a.state===2){a.state=5;a.connection.addStream(a.localStream.stream);a.connection.setRemoteDescription(new RTCSessionDescription(b.message),function(){console.log("Set remote descripiton successfully.");a.connection.createAnswer(function(b){b.sdp=p(b.sdp);a.connection.setLocalDescription(b,function(){console.log("Set local description successfully.");f.sendSignalMessage(a.id,b);console.log("Sent answer.");a.state=5;if(g.length!=0){for(var c=0;c<
g.length;c++){console.log("wenjie: remoteIce33, length:"+g.length+", current:"+c);a.connection.addIceCandidate(g[c])}g=[]}},function(a){console.error("Error occurred while setting local description. Error message:"+a)})},function(){console.log("Create answer failed.")},t)},function(a){console.log("Set remote description failed. Message: "+JSON.stringify(a))})}},A=function(a,b){a&&a.state===5&&a.connection.setRemoteDescription(new RTCSessionDescription(b.message),function(){console.log("Set remote descripiton successfully.");
if(g.length!=0){for(var b=0;b<g.length;b++){console.log("wenjie: remoteIce33, length:"+g.length+", current:"+b);a.connection.addIceCandidate(g[b])}g=[]}},function(a){console.log("Set remote description failed. Message: "+a)})},m=function(a){if(!a||a.connection)return true;try{a.connection=new RTCPeerConnection(n);a.connection.onicecandidate=function(b){b.candidate&&f.sendSignalMessage(a.id,{type:"candidate",candidate:b.candidate.candidate,sdpMid:b.candidate.sdpMid,sdpMLineIndex:b.candidate.sdpMLineIndex})};
a.connection.onaddstream=function(a){console.log("Remote stream added.");a=Woogeen.StreamEvent({type:"stream-subscribed",stream:{stream:a.stream}});c.dispatchEvent(a)};a.connection.onremovestream=function(){console.log("Remote stream removed.");var a=Woogeen.StreamEvent({type:"stream-removed"});c.dispatchEvent(a)};a.connection.oniceconnectionstatechange=function(){if(a){console.log("Ice connection state changed. State: "+a.connection.iceConnectionState);if(a.connection.iceConnectionState==="disconnected"){a.connection.close();
delete e[a.id];c.dispatchEvent(Woogeen.ChatEvent({type:"chat-stopped",peerId:a.id,senderId:a.id}))}if(a.connection.iceConnectionState==="connected"){a.state=6;c.dispatchEvent(Woogeen.ChatEvent({type:"chat-started",peerId:a.id}))}}}}catch(b){console.log("Failed to create PeerConnection, exception: "+b.message);return false}return true},j=function(a){e[a]||(e[a]={state:1,id:a})},q=function(a){return room=JSON.parse(a)},o=function(a,b){if(b){b.localStream=a;b.stream=a;m(b);if(b.state===4||b.state===
2){b.connection.addStream(a.stream);b.connection.createOffer(function(a){a.sdp=p(a.sdp);b.connection.setLocalDescription(a,function(){console.log("Set local descripiton successfully.");f.sendSignalMessage(b.id,a);b.state=5},function(a){console.log("Set local description failed. Message: "+JSON.stringify(a))})},function(){console.log("Create offer failed.")})}}},r=function(a){if(!f)throw Woogeen.Error.P2P_CONN_CLIENT_NOT_INITIALIZED;if(a){var b=e[a];if(b){f.sendVideoStopped(b.id);b.connection.close();
delete e[a];c.dispatchEvent(Woogeen.ChatEvent({type:"chat-stopped",peerId:b.id,senderId:l}))}}else for(var h in e){b=e[h];f.sendVideoStopped(b.id);b.connection.close();delete e[b.id];c.dispatchEvent(Woogeen.ChatEvent({type:"chat-stopped",peerId:b.id,senderId:l}))}},s=function(a){var b=i[a];if(b){r(b.peer.id);if(!f)throw Woogeen.Error.P2P_CONN_CLIENT_NOT_INITIALIZED;f.sendLeaveRoom(a);delete i[a]}},p=function(a){for(var b=a.split("\r\n"),c=0;c<b.length;c++)if(b[c].search("m=audio")!==-1){var e=c;break}if(e===
null)return a;for(c=0;c<b.length;c++)if(b[c].search("opus/48000")!==-1){var d=k(b[c],/:(\d+) opus\/48000/i);if(d){for(var a=b,c=e,f=b[e].split(" "),g=[],i=0,j=0;j<f.length;j++){i===3&&(g[i++]=d);f[j]!==d&&(g[i++]=f[j])}d=g.join(" ");a[c]=d}break}a=e;c=b[a].split(" ");for(d=b.length-1;d>=0;d--)if(f=k(b[d],/a=rtpmap:(\d+) CN\/\d+/i)){f=c.indexOf(f);f!==-1&&c.splice(f,1);b.splice(d,1)}b[a]=c.join(" ");a=e;c=b[a].split(" ");for(d=b.length-1;d>=0;d--)if(f=k(b[d],/a=rtpmap:(\d+) ISAC\/\d+/i)){f=c.indexOf(f);
f!==-1&&c.splice(f,1);b.splice(d,1)}b[a]=c.join(" ");a=e;c=b[a].split(" ");for(d=b.length-1;d>=0;d--)if(f=k(b[d],/a=rtpmap:(\d+) PCMU\/\d+/i)){f=c.indexOf(f);f!==-1&&c.splice(f,1);b.splice(d,1)}b[a]=c.join(" ");a=e;c=b[a].split(" ");for(d=b.length-1;d>=0;d--)if(f=k(b[d],/a=rtpmap:(\d+) PCMA\/\d+/i)){f=c.indexOf(f);f!==-1&&c.splice(f,1);b.splice(d,1)}b[a]=c.join(" ");a=b[e].split(" ");for(c=b.length-1;c>=0;c--)if(d=k(b[c],/a=rtpmap:(\d+) telephone-event\/\d+/i)){d=a.indexOf(d);d!==-1&&a.splice(d,1);
b.splice(c,1)}b[e]=a.join(" ");a=b.join("\r\n");e=a.match(/a=fmtp.*\r\n/);return a=a.replace(e[0],"a=fmtp:111 minptime=10 stereo=1; sprop-stereo=1\r\n")},k=function(a,b){var c=a.match(b);return c&&c.length==2?c[1]:null};c.connect=function(a,b,c){f=new Gab(a,b,c);f.onConnected=u;f.onDisconnected=v;f.onVideoStopped=y;f.onVideoDenied=x;f.onVideoInvitation=w;f.onVideoSignal=B;f.onChatWait=D;f.onChatReady=C;f.onAuthenticated=E};c.disconnect=function(){f&&f.finalize();f=null};c.publish=function(a,b){e[b]||
j(b);peer=e[b];if(peer.state===1){if(!f)throw Woogeen.Error.P2P_CONN_CLIENT_NOT_INITIALIZED;peer.peerId||j(b);peer.state=3;f.sendVideoInvitation(b)}o(a,peer)};c.deny=function(a){if(e[a]&&e[a].state===4){if(!f)throw Woogeen.Error.P2P_CONN_CLIENT_NOT_INITIALIZED;f.sendVideoDenied(a);delete e[a]}};c.stop=r;c.joinRoom=function(a,b){var c=q(a);if(!f)throw Woogeen.Error.P2P_CONN_CLIENT_NOT_INITIALIZED;f.onChatReady=function(a){e[a]||j(a);a=e[a];a.state=2;a.roomId=c.id;a.localStream=b;m(a);i[c.id]||(i[c.id]=
{peer:a})};f.sendJoinRoom(c.id)};c.leaveRoom=function(a){if(a){room=q(a);s(room.id)}else for(var b in i)s(i[b])};return c};
